pipeline {
    agent any
    stages {
        stage('Setup Maven') {
            steps {
                // Maven komutunu global olarak kullanılabilir hale getir
                sh 'cd /usr/bin/ && ln -s /opt/maven/bin/mvn mvn'
            }
        }
        stage('Build') {
            steps {
                sh '/opt/maven/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/opt/maven/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
